# DiffSense MR risk audit job
# Prerequisite: In project Settings → CI/CD → Variables, add DIFFSENSE_TOKEN (Personal Access Token, scope=api, check Mask variable).
# Intranet: Add DIFFSENSE_IMAGE in Variables and use image: $DIFFSENSE_IMAGE below.
# entrypoint: [""] is required; otherwise the job fails with "No such command 'sh'".
diffsense_check:
  stage: diffsense
  image: ghcr.io/goldensupremesaltedfish/diffsense:1.0.0
  entrypoint: [""]
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - diffsense audit --platform gitlab --token "$DIFFSENSE_TOKEN" --project-id "$CI_PROJECT_ID" --mr-iid "$CI_MERGE_REQUEST_IID" --gitlab-url "${GITLAB_URL:-$CI_SERVER_URL}"
  allow_failure: false
