# DiffSense：可发布制品接入。企业只接受 image: xxx/diffsense:1.0，能跑就行。
# Variables: DIFFSENSE_TOKEN（api 权限）。内网配 DIFFSENSE_IMAGE 覆盖 image。
diffsense_check:
  stage: diffsense
  image: ghcr.io/goldensupremesaltedfish/diffsense:1.0.0
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - diffsense audit --platform gitlab --token "$DIFFSENSE_TOKEN" --project-id "$CI_PROJECT_ID" --mr-iid "$CI_MERGE_REQUEST_IID" --gitlab-url "${GITLAB_URL:-$CI_SERVER_URL}"
  allow_failure: false
