# DiffSense：可发布制品接入。企业只接受 image: xxx/diffsense:1.0，能跑就行。
#
# 【配置 GitLab Token】在项目内：Settings → CI/CD → Variables → Add variable
#   Key:   DIFFSENSE_TOKEN
#   Value: 你的 Personal Access Token（需勾选 api 权限）
#   勾选 Mask variable
#
# 内网镜像：同路径增加 DIFFSENSE_IMAGE，job 里写 image: $DIFFSENSE_IMAGE
# 必须加 entrypoint: [""]，否则会报 No such command 'sh'
diffsense_check:
  stage: diffsense
  image: ghcr.io/goldensupremesaltedfish/diffsense:1.0.0
  entrypoint: [""]
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - diffsense audit --platform gitlab --token "$DIFFSENSE_TOKEN" --project-id "$CI_PROJECT_ID" --mr-iid "$CI_MERGE_REQUEST_IID" --gitlab-url "${GITLAB_URL:-$CI_SERVER_URL}"
  allow_failure: false
